language: android
android:
  components:
    - build-tools-22.0.1
    - android-22
    - sysimg-19
    - extra-android-support
    - extra-android-m2repository
licenses:
    - android-sdk-license-bcbbd656
    - '.*intel.+'
script:
  - ./gradlew build 
